<?php
/**
 * Magedelight
 * Copyright (C) 2017 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_ScheduleShipping
 * @copyright Copyright (c) 2017 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<?php $_orders = $block->getOrders() ?>
<?php if ($_orders): ?>
    <table class="email-items">
        <thead>
            <tr>
                <th class="item-info">
                    <?php echo /* @escapeNotVerified */ __('ID'); ?>
                </th>
                <th class="item-info">
                    <?php echo /* @escapeNotVerified */ __('Customer Name'); ?>
                </th>
                <th class="item-qty">
                    <?php echo /* @escapeNotVerified */ __('Delivery Date'); ?>
                </th>
                <th class="item-qty">
                    <?php echo /* @escapeNotVerified */ __('Status'); ?>
                </th>
                <th class="item-qty">
                    <?php echo /* @escapeNotVerified */ __('Grand Total'); ?>
                </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($_orders as $_order): ?>
                <tr>
                    <td class="item-info">
                        <?php echo $block->escapeHtml($_order->getIncrementId()) ?>
                    </td>
                    <td class="customer-name">
                        <?php echo $block->escapeHtml($_order->getCustomerName()) ?>
                    </td>
                    <td class="item-delivery-date">
                        <?php if (!$_order->getDeliveryTimeslot()): ?>
                            <?php echo $block->escapeHtml($_order->getDeliveryDate()) ?><br>
                        <?php else: ?>
                            <?php echo $this->helper('Magedelight\ScheduleShipping\Helper\Data')->getFormatedDate($_order->getDeliveryDate()); ?><br>
                        <?php endif; ?>
                        <?php echo $block->escapeHtml($_order->getDeliveryTimeslot()) ?>
                    </td>
                    <td class="item-status">
                        <?php echo $block->escapeHtml($_order->getStatus()) ?>
                    </td>
                    <td class="item-total">
                        <?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency(number_format($_order->getGrandTotal(), 2), true, false); ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>