<?php
/**
 * Magedelight
 * Copyright (C) 2016 Magedelight <info@magedelight.com>
 *
 * NOTICE OF LICENSE
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://opensource.org/licenses/gpl-3.0.html.
 *
 * @category Magedelight
 * @package Magedelight_ScheduleShipping
 * @copyright Copyright (c) 2016 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<div class="userguide-container">
    <label>To add order information in Order pdf, add the following line of code in `insertOrder()`, where you want to show order delivery information</label>
    <pre>
<code>File Path: vendor/magento/module-sales/Model/Order/Pdf/AbstractPdf.php</code>
<code>
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_deliveryInformation = $_objectManager->create('Magedelight\ScheduleShipping\Helper\Deliveryinfo');
$this->y = $_deliveryInformation->getDeliveryInformation($this->y,$page, $order);
</code>

<label>To add order information in Order Email, add the following line of code in you e-mail template 
where you want to show order delivery information</label>

<code>
{{block class='Magento\\Framework\\View\\Element\\Template' area='frontend'
template='Magedelight_ScheduleShipping::email/order-new/delivery-info.phtml' order=$order}}
</code>
    </pre>
</div>
