<?php
/**
 * Magedelight
 * Copyright (C) 2017 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_ScheduleShipping
 * @copyright Copyright (c) 2017 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
$storeCurrency = $block->getStoreCurrency();
$_order = $block->getOrder();
if ($_order->getDeliveryDate()) {
    if (!($_order->hasInvoices() || $_order->hasShipments())) {
        if ($this->isScheduleShippingEnable() && $this->isScheduleShippingEnableForCustomer()) {
            ?>
    <button type="button" title="Edit" class="action primary editschedulebutton">
        <span>Edit</span>
    </button>
            <?php
    
            if ($this->getDeliveryType() == 1) {
                $date = date_create($_order->getDeliveryDate());
                $deliveryDate = date_format($date, "Y-m-d");
                ?>
        <form action="<?= /* @noEscape */ $this->getUrl('scheduleshipping/order/save'); ?>" method="post">
        <input type="hidden" name="order_id" value="<?= /* @noEscape */ $_order->getId(); ?>" />
        <div id="store-container-main" style="display: none">
            <div class="store-container-inner">
                <div id="delivery-date-box">
                    <label for="delivery-date"><?= /* @noEscape */ $this->getDeliveryDateLabel(); ?> </label>
                    <input class="field required" data-validate="{required:true}" placeholder="Select Delivery Date" readonly="true" dataScope ="shippingAddress.delivery_date" valueUpdate = "keyup" hasFocus = "focused" type="text" id="delivery-date" name="delivery_date" autocomplete="off" value="<?= /* @noEscape */ $deliveryDate; ?>" /><br>
                </div>
                <div class="delivry-charge" style="display:none">
                    <input class="field required" data-validate="{required:true}" placeholder="Delivery charge" dataScope ="shippingAddress.delivery_charge" valueUpdate = "keyup" hasFocus = "focused" type="text" id="custom_fee" name="custom-fee" autocomplete="off" disabled="disable"/>
                </div>

                <?php if ($this->isDeliveryMessageEnable()) { ?>
                    <div class="addtional-message">
                        <span><?= /* @noEscape */ $this->getDeliveryMessage(); ?></span>
                    </div>
                <?php } ?>

                <?php if ($this->getEnableDeliveryDateComment()) { ?>
                    <div id="delivery-comment-box">
                        <label for="delivery_comment"><?= /* @noEscape */ $this->getDeliveryDateCommentLabel(); ?> </label>
                        <textarea id="delivery-comment" name="delivery_comment" class = "field required" autocomplete="off" data-validate="{required:true}" dataScope ="shippingAddress.pickup_date" valueUpdate = "keyup" hasFocus = "focused" placeholder="Enter Comment"> <?= /* @noEscape */ $_order->getDeliveryComment(); ?></textarea>
                    </div>
                <?php } ?>
                <?php if ($this->isEnableCallmeBeforeDelivery()) {
                    $checked = '';
                    if ($_order->getDeliveryCall() == '1') {
                        $checked = 'checked';
                    }
                    ?>
                    <div id="callme_before_delivery">
                        <input type="checkbox" <?= /* @noEscape */ $checked; ?> name="delivery_call" value="Yes"> Call me before Delivery
                    </div>
                <?php } ?>
            </div>
            <button type="submit" style="float:right" title="Save" class="action tocart primary">
                <span>Save</span>
            </button>
        </div>
        </form>

        <script type="text/javascript">

            require(['jquery', 
                'mage/calendar'
            ], function ($) {
                var initMyLib = function () {
                        jQuery(document).ready(function(){
                            jQuery('.editschedulebutton').click(function(){
                                jQuery('#store-container-main').show();
                            });
                        });                        

                        function disabledaywise(date) {
                            var day = date.getDay();
                            var disableday = new Array();
                <?php foreach ($this->getOffDay() as $key => $val) { ?>
                                disableday.push(<?php echo $val; ?>);
        <?php } ?>
                            if ($.inArray(day, disableday) != -1) {
                                return [false];
                            }
                            return [true];
                        }

                        var disabledDays = <?= /* @noEscape */ $this->getOffDate(); ?>;
                        function nationalDays(date) {
                            var m = date.getMonth(), d = date.getDate(), y = date.getFullYear();
                            for (i = 0; i < disabledDays.length; i++) {
                                if ($.inArray((m + 1) + '-' + d + '-' + y, disabledDays) != -1) {
                                    return [false];
                                }
                            }
                            return [true];
                        }

                        function setCustomDate(date) {
                            var arr2 = nationalDays(date);
                            var arr3 = disabledaywise(date);
                            return [(!arr2[0] || !arr3[0]) ? false : true];
                        }
                        var isEnableTime = <?= /* @noEscape */ $this->isEnableTimeInCalender(); ?>;
                        
                        var maxDate = null;
                        <?php if ($this->getMaxIntervalDate()) {
                            ?>
                            maxDate = new Date();
                            maxDate.setDate(maxDate.getDate() + <?= /* @noEscape */$this->getMaxIntervalDate(); ?>);
                            <?php
                        }
                        ?>
                                               
                        jQuery("#delivery-date").datetimepicker({
                            showTimepicker: isEnableTime,
                            hideIfNoPrevNext: true,
                            buttonText: "<?= /* @noEscape */ __('Select Date') ?>",
                            minDate: new Date(),
                            maxDate: maxDate,
                            dateFormat: 'yy-mm-dd',
                            constrainInput: true,
                            beforeShowDay: setCustomDate,
                            onSelect: function (dateText, inst) {

                                // Create date from input value
                                var inputDate = new Date(dateText);

                                // Get today's date
                                var todaysDate = new Date();

                                // Get tomorrow date
                                var tomorrowDate = new Date(new Date().getTime() + 24 * 60 * 60 * 1000);

                                // call setHours to take the time out of the comparison
                                if (inputDate.setHours(0, 0, 0, 0) == todaysDate.setHours(0, 0, 0, 0)) {
                                    // Date equals today's date
                                    var today_charge = <?= /* @noEscape */ $this->getSamedayDeliveryAmount(); ?>;
                                    jQuery('[name="custom-fee"]').val(today_charge);
                                    jQuery('.nextday-delivery').hide();
                                    jQuery('.sameday-delivery').show();
                                } else if (inputDate.setHours(0, 0, 0, 0) == tomorrowDate.setHours(0, 0, 0, 0)) {
                                    // Date equals today's date
                                    var nextday_charge = <?= /* @noEscape */ $this->getNextdayDeliveryAmount(); ?>;
                                    jQuery('[name="custom-fee"]').val(nextday_charge);
                                    jQuery('.sameday-delivery').hide();
                                    jQuery('.nextday-delivery').show();
                                } else {
                                    nocharge = 0;
                                    jQuery('[name="custom-fee"]').val(nocharge);
                                    jQuery('.sameday-delivery').hide();
                                    jQuery('.nextday-delivery').hide();
                                }
                            }
                        });
                }
                initMyLib(); //-> initMyLib is undefined
            });
        </script>

            <?php } elseif ($this->getDeliveryType() == 2) {
                $date = date_create($_order->getDeliveryDate());
                $deliveryDate = date_format($date, "Y-m-d");
                ?>
        <form action="<?= /* @noEscape */ $this->getUrl('scheduleshipping/order/save'); ?>" method="post">
            <input type="hidden" name="order_id" value="<?= /* @noEscape */ $_order->getId(); ?>" />
            <div id="store-container-main" style="display: none">
                <div class="store-container-inner">
                    <div id="delivery-date-box">
                        <label for="delivery-date"><?= /* @noEscape */ $this->getDeliveryDateLabel(); ?> </label><br>
                        <input class="field required" data-validate="{required:true}" placeholder="Select Delivery Date" readonly type="text" id="delivery-date-show" name="delivery_date_show" valueUpdate = "keyup" autocomplete="off" value="<?= /* @noEscape */ $deliveryDate; ?> : <?= /* @noEscape */ $_order->getDeliveryTimeslot(); ?>" />
                        <span id="select-date" class="btnChoice"> </span>
                    </div>
                    <div class="delivry-timeslot" style="display:none">
                        <input class="field required" data-validate="{required:true}" placeholder="Select Delivery Date" readonly type="text" id="delivery-date" name="delivery_date" valueUpdate = "keyup" autocomplete="off" value="<?= /* @noEscape */ $deliveryDate; ?>" />
                        <input class="field required" data-validate="{required:true}" placeholder="Delivery Timeslot" dataScope ="shippingAddress.delivery_timeslot" valueUpdate = "keyup" hasFocus = "focused" type="text" id="delivery-timeslot" name="delivery_timeslot" autocomplete="off" value="<?= /* @noEscape */ $_order->getDeliveryTimeslot(); ?>"/>
                    </div>
                    <?php $timeSlot = $this->getTimeSlot();

                    $classvar = '';
                    if ($timeSlot['maxtimeslot'] == 1) {
                        $classvar = 'timeslot-column-one';
                    } elseif ($timeSlot['maxtimeslot'] == 2) {
                        $classvar = 'timeslot-column-two';
                    } elseif ($timeSlot['maxtimeslot'] == 3) {
                        $classvar = 'timeslot-column-three';
                    }

                    if (count($timeSlot['timeslot']) < 5) {
                        $classvar = $classvar .' timeslot-row-five';
                    }
                    ?>
                    <table id="divChoices" style="display:none;width:auto" class="<?= /* @noEscape */ $classvar; ?>">
                        <thead>
                            <tr>
                                <th align="left" valign="middle">
                                    <div class="choices-header">
                                        <div class="timeslot-close">x</div>
                                        <div class="choices-header-left-aria">Date</div>
                                        <div class="choices-header-right-aria">Time Slots</div>
                                    </div>
                                </th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <td>
                                    <div id="parent">
                                        <table id="fixTable" class="table">
                                            <thead>
                                            </thead>
                                            <tbody>
                                                <?php if ($timeSlot['maxtimeslot']) { ?>
                                                    <?php foreach ($timeSlot['timeslot'] as $rows) { ?>
                                                        <tr >
                                                            <?php foreach ($rows as $column) { ?>
                                                                <td time="<?= /* @noEscape */ $column['time'] ?>" date="<?= /* @noEscape */ $column['date'] ?>" class="<?= /* @noEscape */ ($column['is_enabel']) ? 'btnselect' : 'disabledtd'; ?>" value="<?= /* @noEscape */ $column['value'] ?>"  <?= /* @noEscape */ ($column['price']) ? "price='" . $column['price'] . "'" : '' ?> ><?= /* @noEscape */ $column['label'] ?></td>
                                                            <?php } ?>
                                                        </tr>
                                                    <?php } ?>
                                                <?php } else { ?>
                                                <div class="no-slot"><?= /* @noEscape */ __('Sorry, Delivery time not available.'); ?></div>
                                            <?php } ?>
                                            </tbody>
                                            <tfoot>
                                            </tfoot>
                                        </table>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>


                    <div class="show-delivery-charge">
                        <?php if ($_order->getFee()) { ?>
                        <span>Delivery Charge: <?= /* @noEscape */ $this->helper('Magento\Framework\Pricing\Helper\Data')->currency(number_format($_order->getFee(), 2), true, false); ?></span>
                    <?php } ?>
                    </div>
                    <?php if ($this->isDeliveryMessageEnable()) { ?>
                        <div class="addtional-message">
                            <span><?= /* @noEscape */ $this->getDeliveryMessage(); ?></span>
                        </div>
                    <?php } ?>
                    <div class="delivry-charge" style="display:none">
                        <input class="field required" data-validate="{required:true}" placeholder="Delivery charge" dataScope ="shippingAddress.delivery_charge" valueUpdate = "keyup" hasFocus = "focused" type="text" id="custom_fee" name="custom-fee" autocomplete="off" disabled="disable"/>
                    </div>

                    <?php if ($this->getEnableDeliveryDateComment()) { ?>
                        <div id="delivery-comment-box">
                            <label for="delivery_comment"><?= /* @noEscape */ $this->getDeliveryDateCommentLabel(); ?> </label>
                            <textarea id="delivery-comment" name="delivery_comment" class = "field required" autocomplete="off" data-validate="{required:true}" dataScope ="shippingAddress.pickup_date" valueUpdate = "keyup" hasFocus = "focused" placeholder="Select Delivery Date"> <?= /* @noEscape */ $_order->getDeliveryComment(); ?></textarea>
                        </div>
                    <?php } ?>
                    <?php if ($this->isEnableCallmeBeforeDelivery()) {
                            $checked = '';
                        if ($_order->getDeliveryCall() == '1') {
                            $checked = 'checked';
                        }
                        ?>
                        <div id="callme_before_delivery">
                            <input type="checkbox" <?= /* @noEscape */ $checked; ?> name="delivery_call" value="Yes"> Call me before Delivery
                        </div>
                    <?php } ?>
                </div>
                <button type="submit" style="float:right" title="Save" class="action tocart primary">
                    <span>Save</span>
                </button>
            </div>
        </form>

        <script type="text/javascript">

            require(['jquery', 
                'Magento_Catalog/js/price-utils',
                'tableslotfixer',
                'mage/calendar'
            ], function ($, priceUtils) {
                
                var initMyLib = function () {
                        jQuery(document).ready(function(){
                            jQuery('.editschedulebutton').click(function(){
                                jQuery('#store-container-main').show();
                            });
                        });
                        
                        jQuery('.btnChoice, #delivery-date-show').on('click', function(){
                            jQuery('#divChoices').show();
                            jQuery('.btnselect').on('click', function () {
                                date = $(this).parent().children(':first-child').attr('value');
                                timeslot = $(this).attr('value');
                                datetimeslot = date + ' : ' + timeslot;
                                additionalfees = $(this).attr('price');
                                $('td').removeClass('selected');
                                $(this).addClass('selected');
                                jQuery('#delivery-date-show').val(datetimeslot);
                                jQuery('#delivery-date').val(date);
                                jQuery('#delivery-timeslot').val(timeslot);
                                jQuery('[name="custom-fee"]').val(additionalfees);
                                if (additionalfees) {
                                    //jQuery('div.show-delivery-charge').html('<span>Delivery Charge: '+priceUtils.formatPrice(additionalfees) +'</span>');
                                    jQuery('div.show-delivery-charge').html('<span>Delivery Charge: '+ '<?php echo $storeCurrency;?>' + parseFloat(additionalfees).toFixed(2) +'</span>');
                                }else{
                                    jQuery('div.show-delivery-charge').text('');
                                };
                                jQuery('#divChoices').hide();
                            });

                            jQuery('.timeslot-close').on('click', function () {
                                jQuery('#divChoices').hide();
                            });
                        });

                        var addhour = <?= /* @noEscape */ $this->getTimeslotIntervalHour(); ?>;
                        var date = new Date();
                        var currenttime = Date.UTC(date.getFullYear()
                                , date.getMonth()
                                , date.getDate()
                                , date.getHours() + addhour
                                , date.getMinutes()
                                , date.getSeconds()
                                , date.getMilliseconds()
                                );

                        jQuery("td")
                                .filter(function () {
                                    return jQuery(this).attr("time") < currenttime;
                                })
                                .addClass('disabledtd').removeClass('btnselect');

                        jQuery("#fixTable").tableHeadFixer({'left': 1});
                }
                initMyLib(); //-> initMyLib is undefined
                
            });
        </script>

    <?php } ?>
    <script type="text/javascript">
        var isScheduleShippingEnable = parseInt(<?= /* @noEscape */ $this->isScheduleShippingEnable(); ?>);
        var isDeliveryDateMandatory = parseInt(<?= /* @noEscape */ $this->IsDeliveryDateMandatory(); ?>);
        var minimumorderamount = parseInt(<?= /* @noEscape */ $this->IsDeliveryDateMandatory(); ?>);
    </script>
<?php } else { ?>
    <script type="text/javascript">
        var isScheduleShippingEnable = parseInt(<?= /* @noEscape */ $this->isScheduleShippingEnable(); ?>);
        var isDeliveryDateMandatory = parseInt(<?= /* @noEscape */ $this->IsDeliveryDateMandatory(); ?>);
        var minimumorderamount = 0;
    </script>
<?php }
    }
}
?>