<?php
/**
 * Magedelight
 * Copyright (C) 2017 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_ScheduleShipping
 * @copyright Copyright (c) 2017 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<?php $_order = $block->getOrder() ?>
<?php if ($_order->getDeliveryDate()) { ?>
    <div class="block block-order-details-view dinfo">
        <div class="block-title">
            <strong><?php echo __('Delivery Information') ?></strong>
        </div>
        <div class="block-content">
            <div class="box box-order-shipping-address">
                <strong class="box-title"><span><?php echo __('Delivery Date & Time') ?></span></strong>
                <div class="box-content">
                    <?php
                    if ($_order->getDeliveryTimeslot()) {
                        $date = date_create($_order->getDeliveryDate());
                        $deliveryDate = date_format($date, "Y-m-d");
                        ?>
                        <address><?php echo $deliveryDate; ?></address>
                        <address><?php echo $_order->getDeliveryTimeslot(); ?></address>
                    <?php } else { ?>
                        <address><?php echo $_order->getDeliveryDate(); ?></address>
                    <?php } ?>
                </div>
            </div>

            <?php if ($_order->getFee()) { ?>
                <div class="box box-order-shipping-method">
                    <strong class="box-title">
                        <span><?php echo __('Delivery Charge') ?></span>
                    </strong>
                    <div class="box-content">
                        <?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency(number_format($_order->getFee(), 2), true, false); ?>
                    </div>
                </div>
            <?php } ?>

            <?php if ($_order->getDeliveryCall()) { ?>
                <div class="box box-order-billing-address">
                    <strong class="box-title">
                        <span><?php echo __('Call Before Delivery') ?></span>
                    </strong>
                    <div class="box-content">
                        <address><?php echo "Yes"; ?></address>
                    </div>
                </div>    
            <?php } ?>

            <?php if (!empty($_order->getDeliveryComment())) { ?>
                <div class="box box-order-billing-method">
                    <strong class="box-title">
                        <span><?php echo __('Delivery Comment') ?></span>
                    </strong>
                    <div class="box-content">
                        <?php echo $_order->getDeliveryComment() ?>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
<?php } ?>
