<?php
/**
 * Magedelight
 * Copyright (C) 2017 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_ScheduleShipping
 * @copyright Copyright (c) 2017 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<?php $order = $block->getOrder(); ?>

<?php if ($order): ?>
    <tr>
        <td class="method-info">
            <h3><?php echo /* @escapeNotVerified */ __('Delivery Information'); ?></h3>
            <p>
                <?php echo __("Delivery Date: "); ?>
                <?php if (!$order->getDeliveryTimeslot()): ?>
                    <?php echo $block->escapeHtml($order->getDeliveryDate()) ?><br>
                <?php else: ?>
                    <?php echo $this->helper('Magedelight\ScheduleShipping\Helper\Data')->getFormatedDate($order->getDeliveryDate()); ?><br>
                    <?php echo __("Delivery Time: %1", $block->escapeHtml($order->getDeliveryTimeslot())); ?>
                <?php endif; ?>
            </p>

        </td>
        <td class="method-info">
            <br>
            <?php if ($order->getDeliveryCall()): ?>
                <p><?php echo /* @escapeNotVerified */ __('Call before delivery: Yes'); ?></p>
            <?php endif; ?>
        </td>
    </tr>
    <tr>
        <td class="method-info" colspan="2">
            <?php if ($order->getDeliveryComment()): ?>
                <h3><?php echo __("Delivery Comment: %1", $order->getDeliveryComment()); ?></h3>
            <?php endif; ?>
        </td>
    </tr>
<?php endif; ?>