<div class="field office_number">
   <label class="label" for="office_number"><span><?php /* @escapeNotVerified */ echo __('Office Number') ?></span></label>
    <div class="control">
        <input type="text" id="office_number" name="office_number"  title="<?php /* @escapeNotVerified */ echo __('Office Number') ?>" class="input-text validate-length maximum-length-10 minimum-length-10 validate-digits" autocomplete="off">
    </div>
</div>